on:
  push:
    paths:
      - 'papers.bib' # Only run when this file changes
      - 'preprints.bib' # Only run when this file changes	
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with: { python-version: '3.x' }
      - name: Install dependencies
        run: pip install bibtexparser pylatexenc
      - name: Run update script
        run: |
	python update_cv.py
	python update_research.py
      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add cv.html research.html		
          git commit -m "Auto-update publications from bibtex" || echo "No changes"
          git push
